CC = gcc
CFLAGS = -std=c11 -Wall -Wextra -pedantic -g

# TODO: make the default target build hello and repeat
all:
	@echo "TODO: update Makefile to build hello and repeat"

# TODO: add rules for hello and repeat

clean:
	rm -f hello repeat *.o
